const shopActionType = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESSFUL: 'FETCH_COLLECTION_SUCCESSFUL',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
}

export default shopActionType