const toggleCartHidden = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM_INTO_CART: 'ADD_ITEM_INTO_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_INTO_CART: 'REMOVE_ITEM_INTO_CART'
}

export default toggleCartHidden